### ISSUE TITLE
How to use IPython

### ISSUE THREAD

**Issue by arkhan** [tinyerp/erppeek#77] opened 2015-09-10 01:19 UTC
Hello, 

How to use erppeek into ipython, i use these script:
```python
#!/usr/bin/env python3.4
import erppeek
import IPython


def main():
    global_vars = erppeek.main(interact=False)
    if global_vars:
        IPython.start_ipython(user_ns=global_vars, argv=[])

main() 
```
but only work's when run OpenERP local Server

**Comment by florentx** [comment] 2015-09-16 16:12
Duplicate of issue #51

**Closed by florentx** 2015-09-16 16:12 UTC
